---
title: "My First Markdown"
author: "Cathelijn Tjaden"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Download sleep study data
```{r}
library(readr)
sleep <- read_csv(
    "https://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv")
head(sleep)
```


Plot the data by subject
```{r}
library(ggplot2)
ggplot(sleep, aes(x = Days, y= Reaction)) + 
  geom_point() + 
  geom_smooth() + 
  scale_x_continuous(breaks = seq(0, 8, by =2)) + 
  facet_wrap(~ Subject)
```

```{r}
library(dplyr)
sleep %>%
  group_by(Subject) %>% #takes out the first argument so you can do the analysis sequential
  summarise(mean(Reaction))
```

Mean-center reaction times and plot on a single axis

```{r}
sleep %>%
  group_by(Subject) %>%
  mutate(mean_centered_reaction = Reaction - mean(Reaction)) %>%
  ggplot (aes(x=Days, y = mean_centered_reaction,
              colour = factor (Subject))) + 
  geom_smooth(show.legend = FALSE, se =FALSE)+ 
  scale_x_continuous(breaks = seq(0, 8, by = 2))
```

